services:
  - type: web
    name: polycool
    env: php
    plan: free
    repo: https://github.com/bemvasion-bop/polycool
    branch: main

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

    startCommand: |
      php artisan migrate --force
      php artisan storage:link
      php artisan serve --host 0.0.0.0 --port 10000

    autoDeploy: true
